# INTRODUCTION TO NUMPY LIBRARY OF DATA SCIENCE

What is NumPy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types, with many operations being performed in compiled code for performance. There are several important differences between NumPy arrays and the standard Python sequences:

NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory. The exception: one can have arrays of (Python, including NumPy) objects, thereby allowing for arrays of different sized elements.

NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays. In other words, in order to efficiently use much (perhaps even most) of today’s scientific/mathematical Python-based software, just knowing how to use Python’s built-in sequence types is insufficient - one also needs to know how to use NumPy arrays.

The points about sequence size and speed are particularly important in scientific computing. As a simple example, consider the case of multiplying each element in a 1-D sequence with the corresponding element in another sequence of the same length. If the data are stored in two Python lists, a and b, we could iterate over each element:

c = []

for i in range(len(a)):

    c.append(a[i]*b[i])
This produces the correct answer, but if a and b each contain millions of numbers, we will pay the price for the inefficiencies of looping in Python. We could accomplish the same task much more quickly in C by writing (for clarity we neglect variable declarations and initializations, memory allocation, etc.)

for (i = 0; i < rows; i++): {

  c[i] = a[i]*b[i];

}
This saves all the overhead involved in interpreting the Python code and manipulating Python objects, but at the expense of the benefits gained from coding in Python. Furthermore, the coding work required increases with the dimensionality of our data. In the case of a 2-D array, for example, the C code (abridged as before) expands to

for (i = 0; i < rows; i++): {

  for (j = 0; j < columns; j++): {
  
    c[i][j] = a[i][j]*b[i][j];
  }
}
NumPy gives us the best of both worlds: element-by-element operations are the “default mode” when an ndarray is involved, but the element-by-element operation is speedily executed by pre-compiled C code. In NumPy

c = a * b
does what the earlier examples do, at near-C speeds, but with the code simplicity we expect from something based on Python. Indeed, the NumPy idiom is even simpler! This last example illustrates two of NumPy’s features which are the basis of much of its power: vectorization and broadcasting.

Why is NumPy Fast?
Vectorization describes the absence of any explicit looping, indexing, etc., in the code - these things are taking place, of course, just “behind the scenes” in optimized, pre-compiled C code. Vectorized code has many advantages, among which are:

vectorized code is more concise and easier to read

fewer lines of code generally means fewer bugs

the code more closely resembles standard mathematical notation (making it easier, typically, to correctly code mathematical constructs)

vectorization results in more “Pythonic” code. Without vectorization, our code would be littered with inefficient and difficult to read for loops.

Broadcasting is the term used to describe the implicit element-by-element behavior of operations; generally speaking, in NumPy all operations, not just arithmetic operations, but logical, bit-wise, functional, etc., behave in this implicit element-by-element fashion, i.e., they broadcast. Moreover, in the example above, a and b could be multidimensional arrays of the same shape, or a scalar and an array, or even two arrays of with different shapes, provided that the smaller array is “expandable” to the shape of the larger in such a way that the resulting broadcast is unambiguous. For detailed “rules” of broadcasting see numpy.doc.broadcasting.

Who Else Uses NumPy?
NumPy fully supports an object-oriented approach, starting, once again, with ndarray. For example, ndarray is a class, possessing numerous methods and attributes. Many of its methods are mirrored by functions in the outer-most NumPy namespace, allowing the programmer to code in whichever paradigm they prefer. This flexibility has allowed the NumPy array dialect and NumPy ndarray class to become the de-facto language of multi-dimensional data interchange used in Python.

# HOW TO IMPORT NUMPY

Any time you want to use a package or library in your code, you first need to make it accessible.

In order to start using NumPy and all of the functions available in NumPy, you’ll need to import it. This can be easily done with this import statement:

In [1]:
import numpy as np

# Reading the example code

If you aren’t already comfortable with reading tutorials that contain a lot of code, you might not know how to interpret a code block that looks like this:

In [2]:
a=np.arange(6)
a2=a[np.newaxis, :]
a2.shape

(1, 6)

What’s the difference between a Python list and a NumPy array?

NumPy gives you an enormous range of fast and efficient ways of creating arrays and manipulating numerical data inside them. While a Python list can contain different data types within a single list, all of the elements in a NumPy array should be homogenous. The mathematical operations that are meant to be performed on arrays would be extremely inefficient if the arrays weren’t homogenous.

Why use NumPy?

NumPy arrays are faster and more compact than Python lists. An array consumes less memory and is convenient to use. NumPy uses much less memory to store data and it provides a mechanism of specifying the data types. This allows the code to be optimized even further.

What is an array?

An array is a central data structure of the NumPy library. An array is a grid of values and it contains information about the raw data, how to locate an element, and how to interpret an element. It has a grid of elements that can be indexed in various ways. The elements are all of the same type, referred to as the array dtype.

An array can be indexed by a tuple of nonnegative integers, by booleans, by another array, or by integers. The rank of the array is the number of dimensions. The shape of the array is a tuple of integers giving the size of the array along each dimension.

One way we can initialize NumPy arrays is from Python lists, using nested lists for two- or higher-dimensional data.

In [12]:
a=np.array([1,2,3,4,6,7])

We can access the elements in the array using square brackets. When you’re accessing elements, remember that indexing in NumPy starts at 0. That means that if you want to access the first element in your array, you’ll be accessing element “0”.

In [13]:
print(a[0])

1


# More information about arrays

This section covers 1D array, 2D array, ndarray, vector, matrix

You might occasionally hear an array referred to as a “ndarray,” which is shorthand for “N-dimensional array.” An N-dimensional array is simply an array with any number of dimensions. You might also hear 1-D, or one-dimensional array, 2-D, or two-dimensional array, and so on. The NumPy ndarray class is used to represent both matrices and vectors. A vector is an array with a single dimension (there’s no difference between row and column vectors), while a matrix refers to an array with two dimensions. For 3-D or higher dimensional arrays, the term tensor is also commonly used.


What are the attributes of an array?

An array is usually a fixed-size container of items of the same type and size. The number of dimensions and items in an array is defined by its shape. The shape of an array is a tuple of non-negative integers that specify the sizes of each dimension.

In NumPy, dimensions are called axes. This means that if you have a 2D array that looks like this:

[[0., 0., 0.],

 [1., 1., 1.]]
 
Your array has 2 axes. The first axis has a length of 2 and the second axis has a length of 3.

Just like in other Python container objects, the contents of an array can be accessed and modified by indexing or slicing the array. Unlike the typical container objects, different arrays can share the same data, so changes made on one array might be visible in another.

Array attributes reflect information intrinsic to the array itself. If you need to get, or even set, properties of an array without creating a new array, you can often access an array through its attributes.

# How to create a Basic array

This section covers np.array(), np.zeros(), np.ones(), np.empty(), np.arange(), np.linspace(), dtype

To create a NumPy array, you can use the function np.array().

All you need to do to create a simple array is pass a list to it. If you choose to, you can also specify the type of data in your list.

In [18]:
a=np.array([[1,2,3,4,5],[1,2,3,4,5]])
print("The Creation of First Array:",a)

The Creation of First Array: [[1 2 3 4 5]
 [1 2 3 4 5]]


In [59]:
"""Besides creating an array from a sequence of elements, you can easily create an array filled with 0’s:"""
b=np.zeros(4)
print("The area filled with 0:",b)
"""Or an array filled with 1’s"""
c=np.ones(4)
print("The array filled with 1:",c)
"""Or even an empty array! The function empty creates an array whose initial content is random and depends on the state of the memory. The reason to use empty over zeros (or something similar) is speed - just make sure to fill every element afterwards!."""
d=np.empty(2)
print(d)
"""You can create an array with a range of elements"""
e=np.arange(4)
print("Creating Range of element in array:",e)
"""And even an array that contains a range of evenly spaced intervals. To do this, you will specify the 
first number, last number, and the step size."""
a1=np.arange(2,10,3)
print(a1)
"""You can also use np.linspace() to create an array with values that are spaced linearly in a specified interval:"""
a2=np.linspace(0,10,num=5)
a2

"""Specifying your data type"""

"""While the default data type is floating point (np.float64), you can explicitly specify which data type you want using the dtype keyword."""
a1=np.ones(2,dtype=np.int64)
print(a1)

The area filled with 0: [0. 0. 0. 0.]
The array filled with 1: [1. 1. 1. 1.]
[5.e-324 5.e-324]
Creating Range of element in array: [0 1 2 3]
[2 5 8]
[1 1]


# ADDING,REMOVING AND SORTING ELEMENT IN THE ARRAY

This section covers np.sort(), np.concatenate()

Sorting an element is simple with np.sort(). You can specify the axis, kind, and order when you call the function.


In [41]:
"""Sorting element in the array Using Numpy Library"""
arr=np.array([1,10,8,9,15,7,18,77])
print(arr)
np.sort(arr)

[ 1 10  8  9 15  7 18 77]


array([ 1,  7,  8,  9, 10, 15, 18, 77])

In [45]:
a1=np.array([1,2,3,4,5])
a2=np.array([1,4,5,6,7])
c=np.concatenate((a1,a2))
np.sort(c)

array([1, 1, 2, 3, 4, 4, 5, 5, 6, 7])

In [48]:
a=np.array([[1,2,3],[3,4,5]])
b=np.array([[10,9,8]])
np.concatenate((a,b),axis=0)

array([[ 1,  2,  3],
       [ 3,  4,  5],
       [10,  9,  8]])

# Shape and Size of an Array

ndarray.ndim will tell you the number of axes, or dimensions, of the array.

ndarray.size will tell you the total number of elements of the array. This is the product of the elements of the array’s shape.

ndarray.shape will display a tuple of integers that indicate the number of elements stored along each dimension of the array. If, for example, you have a 2-D array with 2 rows and 3 columns, the shape of your array is (2, 3).

In [64]:
 array_example = np.array([[[0, 1, 2, 3],
                            [4, 5, 6, 7]],

                           [[0, 1, 2, 3],
                            [4, 5, 6, 7]],

                           [[0 ,1 ,2, 3],
                            [4, 5, 6, 7]]])
    

"""To find the number of dimensions of the array"""
print("The no of dimensions:",array_example.ndim)
"""To find the total number of elements in the array, run"""
print("The total no of elements is:",array_example.size)
"""And to find the shape of your array"""
print("the shape of the array is:",array_example.shape)
"""Reshape of a Array"""
a=np.arange(6)
print("The Shape Of the Array is:",a)
b=a.reshape(3,2)
print("After Reshaping of the Array")
print(b)
print()
"""With np.reshape, you can specify a few optional parameters"""
print(np.reshape(a,newshape=(1,6), order='C'))

The no of dimensions: 3
The total no of elements is: 24
the shape of the array is: (3, 2, 4)
The Shape Of the Array is: [0 1 2 3 4 5]
After Reshaping of the Array
[[0 1]
 [2 3]
 [4 5]]

[[0 1 2 3 4 5]]


# How to convert a 1D array into a 2D array (how to add a new axis to an array

This section covers np.newaxis, np.expand_dims

You can use np.newaxis and np.expand_dims to increase the dimensions of your existing array.

Using np.newaxis will increase the dimensions of your array by one dimension when used once. This means that a 1D array will become a 2D array, a 2D array will become a 3D array, and so on.

In [68]:
a=np.array([1,2,3,4,5])
print("This is a 1-D Array:",a.shape)
#Converting it to 2D Array 
a2=a[np.newaxis,:]
print("Converting it to 2D array:",a2.shape)

This is a 1-D Array: (5,)
Converting it to 2D array: (1, 5)


Or, for a column vector, you can insert an axis along the second dimension:

In [69]:
column_vector=np.array([1,2,3,4,5])
print("This is a 1-D Array:",a.shape)
#Converting it to 2D Array 
a2=a[:,np.newaxis]
print("Converting it to 2D array:",a2.shape)

This is a 1-D Array: (5,)
Converting it to 2D array: (5, 1)


In [76]:
"""You can also expand an array by inserting a new axis at a specified position with np.expand_dims."""
print("Using np.expand_dims for converting 1D Array into 2D Array")
a=np.array([1,2,3,4,5,6])
print(a.shape)
b=np.expand_dims(a,axis=0) # axis=0 is for rows
print(b.shape)
"""You can add an axis at index position 0 with:"""
c=np.expand_dims(a,axis=1) # axis=1 is for column
print(c.shape)

Using np.expand_dims for converting 1D Array into 2D Array
(6,)
(1, 6)
(6, 1)


# Indexing and slicing

You can index and slice NumPy arrays in the same ways you can slice Python lists.

In [85]:
a=np.array([[1,2,3],[3,4,5]])
print(a[0][1])
print(a[0][-1])
print(a[0][1:])

2
3
[2 3]


You may want to take a section of your array or specific array elements to use in further analysis or additional operations. To do that, you’ll need to subset, slice, and/or index your arrays.

If you want to select values from your array that fulfill certain conditions, it’s straightforward with NumPy.

In [89]:
print(a[a>=5])

[5]


In [90]:
"""You can select elements that are divisible by 2"""
a2=a[a%2==0]
print(a2)

[2 4]


In [93]:
"""Or you can select elements that satisfy two conditions using the & and | operators"""
a2=(a>2) & (a<5)
print(a2)

[[False False  True]
 [ True  True False]]


In [92]:
"""You can also make use of the logical operators & and | in order to return boolean values that specify whether or not the values in an array fulfill a certain condition. This can be useful with arrays that contain names or other categorical values."""
a2=a[(a>2) | (a<5)]
print(a2)

[1 2 3 3 4 5]


# How to create an array from existing data

This section covers slicing and indexing, np.vstack(), np.hstack(), np.hsplit(), .view(), copy()

In [97]:
a=np.arange(1,11)
print(a)
"""You can create a new array from a section of your array any time by specifying where you want to slice your array."""
arr1=a[3:8]
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10]
[4 5 6 7 8]


Here, you grabbed a section of your array from index position 3 through index position 8.

You can also stack two existing arrays, both vertically and horizontally. Let’s say you have two arrays, a1 and a2:

In [102]:
a1=np.array([[1,1],
             
             [2,2]])

a2=np.array([[3,3],
            
            [4,4]])

"""You can stack them vertically with vstack"""
print("Vertical Stacking")
print(np.vstack((a1,a2)))
print("Horizontal Stacking")
print()
"""Or stack them horizontally with hstack:"""
print(np.hstack((a1,a2)))

Vertical Stacking
[[1 1]
 [2 2]
 [3 3]
 [4 4]]
Horizontal Stacking

[[1 1 3 3]
 [2 2 4 4]]


In [110]:
"""You can split an array into several smaller arrays using hsplit. You can specify either the number of equally shaped arrays to return or the columns after which the division should occur."""
a=np.arange(1,25).reshape(2,12)
print(a)
"""If you wanted to split this array into three equally shaped arrays."""
print()
print(np.hsplit(a,3))
"""If you wanted to split your array after the third and fourth column."""
print()
print(np.hsplit(a, (3,4)))

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]

[array([[ 1,  2,  3,  4],
       [13, 14, 15, 16]]), array([[ 5,  6,  7,  8],
       [17, 18, 19, 20]]), array([[ 9, 10, 11, 12],
       [21, 22, 23, 24]])]

[array([[ 1,  2,  3],
       [13, 14, 15]]), array([[ 4],
       [16]]), array([[ 5,  6,  7,  8,  9, 10, 11, 12],
       [17, 18, 19, 20, 21, 22, 23, 24]])]


You can use the view method to create a new array object that looks at the same data as the original array (a shallow copy).

Views are an important NumPy concept! NumPy functions, as well as operations like indexing and slicing, will return views whenever possible. This saves memory and is faster (no copy of the data has to be made). However it’s important to be aware of this - modifying data in a view also modifies the original array!

In [115]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b1=a[0,:]
b1
b1[0]=99
print(b1)
print()
print(a)

[99  2  3  4]

[[99  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [116]:
"""Using the copy method will make a complete copy of the array and its data (a deep copy). To use this on your array"""
b2=a.copy()
print(b2)

[[99  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


# Basic Array Operations

This section covers addition, subtraction, multiplication, division, and more

Once you’ve created your arrays, you can start to work with them. Let’s say, for example, that you’ve created two arrays, one called “data” and one called “ones”

In [125]:
"""You can add the arrays together with the plus sign."""
data=np.array([1,2])
ones=np.ones(2,dtype=int)
print("Basic Array Operations:")
print()
print("The addition of two array:",data+ones)
print("The substraction of two array:",data - ones)
print("The multiplication of array:",data  * data)
print("the division of two array:",data / data)

Basic Array Operations:

The addition of two array: [2 3]
The substraction of two array: [0 1]
The multiplication of array: [1 4]
the division of two array: [1. 1.]


In [126]:
"""Basic operations are simple with NumPy. If you want to find the sum of the elements in an array, you’d use sum(). This works for 1D arrays, 2D arrays, and arrays in higher dimensions."""
a=np.array([1,2,3,4,5])
a.sum()

15

In [132]:
"""To add the rows or the columns in a 2D array, you would specify the axis."""

a=np.array([[1,1],[2,2]])
a.sum(axis=0)

array([3, 3])

In [133]:
"""You can sum the columns"""
a=np.array([[1,1,1],[2,2,2]])
a.sum(axis=1)

array([3, 6])

# Broadcasting

There are times when you might want to carry out an operation between an array and a single number (also called an operation between a vector and a scalar) or between arrays of two different sizes. For example, your array (we’ll call it “data”) might contain information about distance in miles but you want to convert the information to kilometers. You can perform this operation with

In [134]:
data=np.array([[1,2],[3,4]])
data * 1.6

array([[1.6, 3.2],
       [4.8, 6.4]])

NumPy understands that the multiplication should happen with each cell. That concept is called broadcasting. Broadcasting is a mechanism that allows NumPy to perform operations on arrays of different shapes. The dimensions of your array must be compatible, for example, when the dimensions of both arrays are equal or when one of them is 1. If the dimensions are not compatible, you will get a ValueError.

# More useful array operations

This section covers maximum, minimum, sum, mean, product, standard deviation, and more

NumPy also performs aggregation functions. In addition to min, max, and sum, you can easily run mean to get the average, prod to get the result of multiplying the elements together, std to get the standard deviation, and more.

In [137]:
print(data.max())

print(data.min())

print(data.sum())

4
1
10


In [138]:
 a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
               [0.54627315, 0.05093587, 0.40067661, 0.55645993],
               [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

4.8595784

It’s very common to want to aggregate along a row or column. By default, every NumPy aggregation function will return the aggregate of the entire array. To find the sum or the minimum of the elements in your array

In [144]:
"The max of the array"

print("The max of the array:",a.max())
"The sum of the array"
print("The sum of the array:",a.sum())

"The min of the array"
print("The minimum of the array:",a.min())

The max of the array: 0.82485143
The sum of the array: 4.8595784
The minimum of the array: 0.05093587


You can specify on which axis you want the aggregation function to be computed. For example, you can find the minimum value within each column by specifying axis=0.

In [145]:
a.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

The four values listed above correspond to the number of columns in your array. With a four-column array, you will get four values as your result.

# Creating Matrices

You can pass Python lists of lists to create a 2-D array (or “matrix”) to represent them in NumPy.

In [146]:
a=np.array([[1,1],[2,2]])
a

array([[1, 1],
       [2, 2]])

In [153]:
"""Indexing and slicing operations are useful when you’re manipulating matrices"""
print(a[0])
print(a[1])
print(a[0][0:1])
print(a[1][1])

[1 1]
[2 2]
[1]
2


In [154]:
"""You can aggregate matrices the same way you aggregated vectors"""
print(a.max())
print(a.min())
print(a.sum())

2
1
6


In [157]:
"""You can aggregate all the values in a matrix and you can aggregate them across columns or rows using the axis parameter"""
print(a.max(axis=0))
print(a.min(axis=1))

[2 2]
[1 2]


In [158]:
"""Once you’ve created your matrices, you can add and multiply them using arithmetic operators if you have two matrices that are the same size."""
a=np.array([[1,1],[2,2]])
b=np.array([[2,2],[3,3]])
a + b

array([[3, 3],
       [5, 5]])

In [159]:
"""You can do these arithmetic operations on matrices of different sizes, but only if one matrix has only one column or one row. In this case, NumPy will use its broadcast rules for the operation."""
data=np.array([[1,1],[2,2]])
ones=np.array([1,1])
data+ones

array([[2, 2],
       [3, 3]])

In [162]:
"""Be aware that when NumPy prints N-dimensional arrays, the last axis is looped over the fastest while the first 
axis is the slowest."""
np.ones((4,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [171]:
"""There are often instances where we want NumPy to initialize the values of an array. 
NumPy offers functions like ones() and zeros(), and the random.Generator class for random 
number generation for that. All you need to do is pass in the number of elements you want it to generate."""
np.ones(3)

np.zeros(3)


rng=np.random.default_rng(2)

rng.random(3)

array([0.26161213, 0.29849114, 0.81422574])

In [173]:
"""You can also use ones(), zeros(), and random() to create a 2D array if you give them a tuple describing the dimensions of the matrix:"""
np.ones((3,2))

np.zeros((3,2))

rng.random((3,2))

array([[0.18790107, 0.05514663],
       [0.27496937, 0.65743301],
       [0.56226566, 0.15006226]])

# Generating Random Numbers

The use of random number generation is an important part of the configuration and evaluation of many numerical and machine learning algorithms. Whether you need to randomly initialize weights in an artificial neural network, split data into random sets, or randomly shuffle your dataset, being able to generate random numbers (actually, repeatable pseudo-random numbers) is essential.

With Generator.integers, you can generate random integers from low (remember that this is inclusive with NumPy) to high (exclusive). You can set endpoint=True to make the high number inclusive.

You can generate a 2 x 4 array of random integers between 0 and 4 with

In [175]:
rng.integers(5,size=(2,4))

array([[3, 2, 3, 3],
       [4, 2, 1, 3]], dtype=int64)

# How to get unique items and counts

This section covers np.unique()

You can find the unique elements in an array easily with np.unique.

In [2]:
import numpy as np
a=np.array([11,12,13,14,15,15,16,17,18,19,20])


array([11, 12, 13, 14, 15, 15, 16, 17, 18, 19, 20])

In [3]:
"""you can use np.unique to print the unique values in your array"""
unique_values=np.unique(a)
unique_values

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [5]:
"""To get the indices of unique values in a NumPy array (an array of first index positions of unique values in the array), just pass the return_index argument in np.unique() as well as your array."""
unique_values,indices_list=np.unique(a ,return_index=True)
print("An array of first index positions of unique values in the array:",indices_list)

An array of first index positions of unique values in the array: [ 0  1  2  3  4  6  7  8  9 10]


In [7]:
"""You can pass the return_counts argument in np.unique() along with your array to get the frequency count of unique values in a NumPy array."""
unique_values,occurence_count=np.unique(a, return_counts=True)
occurence_count

array([1, 1, 1, 1, 2, 1, 1, 1, 1, 1], dtype=int64)

In [9]:
"""This also works with 2D arrays"""
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[1,2,3,4]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [26]:
unique_values=np.unique(a)
print(unique_values)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [29]:
"""If the axis argument isn’t passed, your 2D array will be flattened.

If you want to get the unique rows or columns, make sure to pass the axis argument. To find the unique rows, specify axis=0 and for columns, specify axis=1. """

unique_values=np.unique(a,axis=0)
print(unique_values)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 1  2  3  4]]


In [36]:
"""Summing all the unique values code"""

unique_rows,indices_list,occurence_count=np.unique(a, axis=0, return_index=True,return_counts=True)
print(unique_rows)
print()
print(indices_list)
print()
print(occurence_count)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[0 1 2]

[2 1 1]


# Transposing and reshaping a matrix

This section covers arr.reshape(), arr.transpose(), arr.T()

It’s common to need to transpose your matrices. NumPy arrays have the property T that allows you to transpose a matrix.

You may also need to switch the dimensions of a matrix. This can happen when, for example, you have a model that expects a certain input shape that is different from your dataset. This is where the reshape method can be useful. You simply need to pass in the new dimensions that you want for the matrix.

In [46]:
data=np.arange(1,7)
print(data)

a=data.reshape(2,3)
print(a)

b=data.reshape(3,2)
print(b)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [50]:
"""You can also use .transpose to reverse or change the axes of an array according to the values you specify."""

arr=np.arange(6).reshape((3,2))
print()
print(arr)
print()
arr1=arr.transpose()
print(arr1)


[[0 1]
 [2 3]
 [4 5]]

[[0 2 4]
 [1 3 5]]


# How to reverse an array

This section covers np.flip

NumPy’s np.flip() function allows you to flip, or reverse, the contents of an array along an axis. When using np.flip, specify the array you would like to reverse and the axis. If you don’t specify the axis, NumPy will reverse the contents along all of the axes of your input array.

In [53]:
print("Reversing a 1-D array")

a=np.arange(6)
print("The Original Array is",a)
print()
print("After Reversing the Array")
b=np.flip(a)
print()
print(b)

The Original Array is [0 1 2 3 4 5]

After Reversing the Array

[5 4 3 2 1 0]


In [69]:
print("Reversing A 2-D Array")
print()
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)

flip_array=np.flip(a)
print()
print(flip_array)


print("You can easily reverse only the rows with")

flip_rows=np.flip(a,axis=0)
print()
print(flip_rows)

print("You can easily reverse only the columns with")


flip_columns=np.flip(a,axis=1)
print()
print(flip_columns)


"""You can also reverse the contents of only one column or row. For example, you can reverse the contents of the row at index position 1 (the second row):"""

a[:]=np.flip(a[:])
print()
print(a)


"""You can also reverse the column at index position 1 (the second column):"""

a[:,1] = np.flip(a[:,1])
print()
print(a)

Reversing A 2-D Array

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]
You can easily reverse only the rows with

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]
You can easily reverse only the columns with

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]

[[12  3 10  9]
 [ 8  7  6  5]
 [ 4 11  2  1]]


# Reshaping and flattening multidimensional arrays:-

This section covers .flatten(), ravel()

There are two popular ways to flatten an array: .flatten() and .ravel(). The primary difference between the two is that the new array created using ravel() is actually a reference to the parent array (i.e., a “view”). This means that any changes to the new array will affect the parent array as well. Since ravel does not create a copy, it’s memory efficient.



In [82]:
 x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(x)
print()
print("You can use flatten to flatten your array into a 1D array")
    
faltten=x.flatten()
print()
print(faltten)

print()
print("When you use flatten, changes to your new array won’t change the parent array.")

a1=x.flatten()
a1[0]=99
print()
print(x)
print()
print(a1)
print()
print("But when you use ravel, the changes you make to the new array will affect the parent array")

a2=x.ravel()
a2[0]=97
print()
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

You can use flatten to flatten your array into a 1D array

[ 1  2  3  4  5  6  7  8  9 10 11 12]

When you use flatten, changes to your new array won’t change the parent array.

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[99  2  3  4  5  6  7  8  9 10 11 12]

But when you use ravel, the changes you make to the new array will affect the parent array

[[97  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
